@MessageThreadAPI_HostAddress = http://localhost:5067

### Get messages
GET {{MessageThreadAPI_HostAddress}}/api/messages
Content-Type: application/json

### Create messages
POST {{MessageThreadAPI_HostAddress}}/api/messages
Content-Type: application/json

{
    "text": "Hi, to the world!"
}

# ###
# GET {{MessageThreadAPI_HostAddress}}/api/Messages/1